### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by MamaShip** [MamaShip/MR-Tracker#1]
missing these basic functions:

- [x] get the default branch of repo
- [x] generate changelog to file
- [ ] read old changelog file and avoid overwrite
- [x] post the change list to new issue
- [ ] user config (save & load)
- [x] output format
